'use client';

import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Icon } from '@iconify/react';

import {
  CRUDTemplate,
  CRUDModal,
  useCRUD,
  CRUDColumn,
  CRUDField,
} from '@/components/DataTable';
import { NotificationModal } from '@/components/notification-popup';
import type { Patient } from '@/types/appointment';

type PatientRow = Patient & {
  createdAt?: string;
  updatedAt?: string;
};

const GENDER_OPTIONS = [
  { key: 'male', label: 'Nam' },
  { key: 'female', label: 'Nữ' },
];

export default function PatientManager() {
  const [patients, setPatients] = useState<PatientRow[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const {
    data,
    filteredData,
    setFilteredData,
    searchTerm,
    setSearchTerm,
    filterValue,
    setFilterValue,
    isModalOpen,
    setIsModalOpen,
    editingItem,
    showDeleteModal,
    setShowDeleteModal,
    deletingItem,
    handleAdd,
    handleEdit,
    handleDelete,
    handleSave,
    confirmDelete,
    showSuccess,
    showError,
  } = useCRUD<PatientRow>(patients);

  // Fetch patients on mount
  useEffect(() => {
    fetchPatients();
  }, []);

  // Sync filtered data when base data changes
  useEffect(() => {
    setFilteredData(patients);
  }, [patients, setFilteredData]);

  // Apply client-side filters
  useEffect(() => {
    const term = searchTerm.trim().toLowerCase();
    const filtered = patients.filter(p => {
      const matchSearch = term
        ? [p.name, p.phone, p.patient_id]
            .filter(Boolean)
            .some(v => String(v).toLowerCase().includes(term))
        : true;
      const matchGender =
        filterValue === 'all' ? true : p.gender === (filterValue as any);
      return matchSearch && matchGender;
    });
    setFilteredData(filtered);
  }, [searchTerm, filterValue, patients, setFilteredData]);

  const fetchPatients = async () => {
    try {
      setIsLoading(true);
      const res = await axios.get('/api/patients', {
        params: { page: 1, limit: 100 },
      });
      const items: PatientRow[] = res.data?.items ?? res.data ?? [];
      setPatients(items);
    } catch (error) {
      console.error('Failed to fetch patients', error);
      showError('Lỗi', 'Không thể tải danh sách bệnh nhân. Vui lòng thử lại.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleSavePatient = async (patientData: PatientRow) => {
    try {
      setIsLoading(true);
      if (editingItem?._id) {
        // Update
        const res = await axios.put(`/api/patients/${editingItem._id}`, {
          name: patientData.name,
          gender: patientData.gender,
          birth_date: patientData.birth_date,
          phone: patientData.phone,
          address: patientData.address,
          id_card: patientData.id_card,
        });
        handleSave(res.data);
      } else {
        // Create (patient_id auto-generated by model)
        const res = await axios.post('/api/patients', {
          name: patientData.name,
          gender: patientData.gender,
          birth_date: patientData.birth_date,
          phone: patientData.phone,
          address: patientData.address,
          id_card: patientData.id_card,
        });
        handleSave(res.data);
      }
      showSuccess(
        'Thành công',
        editingItem
          ? 'Cập nhật bệnh nhân thành công!'
          : 'Thêm bệnh nhân thành công!'
      );
      fetchPatients();
    } catch (error: any) {
      const message =
        error?.response?.data?.error || 'Xử lý thất bại. Vui lòng thử lại.';
      showError('Lỗi', message);
    } finally {
      setIsLoading(false);
      setIsModalOpen(false);
    }
  };

  const handleDeletePatient = async () => {
    if (!deletingItem?._id) return;
    try {
      setIsLoading(true);
      await axios.delete(`/api/patients/${deletingItem._id}`);
      confirmDelete();
      fetchPatients();
    } catch (error) {
      console.error('Failed to delete patient', error);
      showError('Lỗi', 'Không thể xóa bệnh nhân. Vui lòng thử lại.');
    } finally {
      setIsLoading(false);
    }
  };

  const columns: CRUDColumn<PatientRow>[] = [
    { key: 'patient_id', label: 'Mã BN', width: '120px' },
    { key: 'name', label: 'Họ và tên' },
    { key: 'phone', label: 'SĐT', width: '140px' },
    {
      key: 'gender',
      label: 'Giới tính',
      width: '120px',
      render: value =>
        value === 'male' ? 'Nam' : value === 'female' ? 'Nữ' : '',
    },
    {
      key: 'birth_date',
      label: 'Ngày sinh',
      width: '150px',
      render: value =>
        value ? new Date(value).toLocaleDateString('vi-VN') : '',
    },
    { key: 'id_card', label: 'CMND/CCCD', width: '150px' },
    { key: 'address', label: 'Địa chỉ' },
  ];

  const fields: CRUDField<PatientRow>[] = [
    {
      key: 'name',
      label: 'Họ và tên',
      type: 'text',
      placeholder: 'Nhập họ và tên',
      required: true,
    },
    {
      key: 'gender',
      label: 'Giới tính',
      type: 'select',
      placeholder: 'Chọn giới tính',
      options: GENDER_OPTIONS,
      required: true,
    },
    {
      key: 'birth_date',
      label: 'Ngày sinh',
      type: 'date',
      required: true,
    },
    {
      key: 'phone',
      label: 'Số điện thoại',
      type: 'text',
      placeholder: 'Nhập số điện thoại',
      required: true,
    },
    {
      key: 'id_card',
      label: 'CMND/CCCD',
      type: 'text',
      placeholder: 'Nhập số CMND/CCCD',
      required: true,
    },
    {
      key: 'address',
      label: 'Địa chỉ',
      type: 'text',
      placeholder: 'Nhập địa chỉ',
      required: true,
    },
  ];

  return (
    <>
      <CRUDTemplate
        title='Quản lý Bệnh nhân'
        description='Quản lý thông tin bệnh nhân trong hệ thống'
        data={data}
        filteredData={filteredData}
        searchTerm={searchTerm}
        setSearchTerm={setSearchTerm}
        filterValue={filterValue}
        setFilterValue={setFilterValue}
        filterOptions={[
          { key: 'male', label: 'Nam' },
          { key: 'female', label: 'Nữ' },
        ]}
        searchFields={['name', 'phone', 'patient_id'] as any}
        columns={columns}
        onAdd={handleAdd}
        onEdit={handleEdit}
        onDelete={handleDelete}
        emptyStateIcon='lucide:users'
        emptyStateMessage='Không tìm thấy bệnh nhân nào'
        addButtonText='Thêm bệnh nhân'
        searchPlaceholder='Tìm theo tên, SĐT, mã bệnh nhân...'
        filterPlaceholder='Lọc theo giới tính'
      />

      {/* Add/Edit Modal */}
      <CRUDModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingItem ? 'Chỉnh sửa Bệnh nhân' : 'Thêm Bệnh nhân Mới'}
        data={editingItem || ({} as PatientRow)}
        onSave={handleSavePatient}
        fields={fields}
        isLoading={isLoading}
      />

      {/* Delete Confirmation */}
      <NotificationModal
        isOpen={showDeleteModal}
        onClose={() => setShowDeleteModal(false)}
        type='error'
        title='Xác nhận xóa bệnh nhân'
        message={`Bạn có chắc chắn muốn xóa bệnh nhân "${deletingItem?.name}" không? Hành động này không thể hoàn tác.`}
        confirmText='Xóa'
        cancelText='Hủy'
        showCancel={true}
        onConfirm={handleDeletePatient}
        onCancel={() => setShowDeleteModal(false)}
      />
    </>
  );
}
